language: php

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.0
      env: L5_VER=4
    - php: 7.0
      env: L5_VER=5
    - php: 7.1
      env: L5_VER=4
    - php: 7.1
      env: L5_VER=5
    - php: 7.1
      env: L5_VER=6
    - php: 7.2
      env: L5_VER=4
    - php: 7.2
      env: L5_VER=5
    - php: 7.2
      env: L5_VER=6

script:
- vendor/bin/phpunit

before_install:
  - composer require "illuminate/support:5.${L5_VER}.*" --no-update -v
  - composer require "illuminate/console:5.${L5_VER}.*" --no-update -v
  - composer require "orchestra/testbench:3.${L5_VER}.*" --no-update -v
  - [ '4' = $L5_VER ] && composer require "phpunit/phpunit:~5.7" --no-update -v

install: composer install --no-interaction

notifications:
  email: false
