language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
  - '7.2'
  - '7.3'
  - '7.4'

env:
  - LARAVEL=6.0
  - LARAVEL=6.20
  - LARAVEL=7.0
  - LARAVEL=7.30
  - LARAVEL=8.0
  - LARAVEL=8.17

matrix:
  exclude:
    - php: '8.0'
      env: 'LARAVEL=6.0'
    - php: '8.0'
      env: 'LARAVEL=7.0'
    - php: '8.0'
      env: 'LARAVEL=8.0'

script:
  - vendor/bin/phpunit

before_install:
  - MINOR=`echo $LARAVEL | sed 's/[6|7|8]\.\([0-9]\+\)/\1/'`
  - '[[ $LARAVEL =~ ^7\.[0-9]+$ ]] && MAJOR=7 || MAJOR=6'
  - '[[ $LARAVEL =~ ^8\.[0-9]+$ ]] && MAJOR=8 || true'
  - echo "Testing against Laravel ${MAJOR}.${MINOR}"
  - composer require "illuminate/support:${MAJOR}.${MINOR}.*" --no-update -v
  - composer require "illuminate/console:${MAJOR}.${MINOR}.*" --no-update -v

install: composer install --no-interaction

notifications:
  email: false
  slack:
    secure: C+rQ1lGvlRPxFqMpgtZYlQdbaOnsKmuvFzsZ1RFdTyNT980B0qxMGjhjCrPwY47hYsMHyS4ouWwNgle5WdxBEE4JVqTdGsos5N7eq4ScODcGuSVsW1XqdmflWAsHPRgbUq2iGyyadx8aLoVxwmK8GOKKwJXW1WRJScocBS5muLtsf17LKqx0h2c0mtauLadmupTAGmm54vlYEjSvl5UR26Evd3ovRpizKqh72cG9Z+UEKVI5uuMP4RdzmPHatI7rx9JLW5A1uMe2Y/BuZX0NmsLRGnIlXzQD8K1Es9ELjyaiz9UlZmz1uBTGvA/RBpHkBbzNB8thHyU1hsPt1QvQlQcD/9tjL3/sdKlDQAmkJIBz7e8dAxcXFdt8dUt77ZMi3V3qjbXMtdz6aOnPCTKnkfVv5eaa+X7oKdduJpGlD1LbAC5xalsgux36gFscCCfgKgbP7kXScOxFUUq1YYlxktb4qAopcoK7EE/5p1RjScuSW5MdATVrOhQEGVgzBRQuT4SBw0waGxMPqDivUyYv4FceW6PNF9MKi1j9zK3uIIrvX/WO+gKrZkoPxt3H1czSahuZXw/VKZ9emGuMdQxHSS9dlLnqobA/hNL7rD+CNZdmsCOLr+40ZYF31ND0W7s/+FJK0tR6ySFVF87RL2B0hsETF2SHqVs2gM6CufyV2TQ=
